### ISSUE TITLE
IllegalArgumentException for an empty `application/json` body

### ISSUE THREAD

**Issue by miikka** [metosin/muuntaja#41]
If you use `muuntaja.middleware/wrap-format-request` and do a HTTP request with the header 'Content-Type: application/json` and with an empty body, Muuntaja throws an IllegalArgumentException. I think that empty bodies should be just ignored.

A stacktrace from a Kekkonen hello world app:

```
clojure.lang.ExceptionInfo: Malformed application/json request. {:type :muuntaja/decode, :default-format "application/json", :format "application/json", :charset "utf-8", :request {:remote-addr "0:0:0:0:0:0:0:1", :params {}, :headers {"origin" "http://localhost:5000", "host" "localhost:5000", "content-type" "application/json", "content-length" "0", "referer" "http://localhost:5000/api-docs/index.html", "connection" "keep-alive", "accept" "application/json", "accept-language" "fi-fi", "accept-encoding" "gzip, deflate", "dnt" "1", "kekkonen.mode" "invoke"}, :async-channel #object[org.httpkit.server.AsyncChannel 0x37ba91df "/0:0:0:0:0:0:0:1:5000<->/0:0:0:0:0:0:0:1:49756"], :server-port 5000, :muuntaja/request #FormatAndCharset{:format "application/json", :charset "utf-8"}, :content-length 0, :form-params {}, :websocket? false, :query-params {}, :content-type "application/json", :character-encoding "utf8", :uri "/api/sample/inc!", :server-name "localhost", :query-string nil, :muuntaja/response #FormatAndCharset{:format "application/json", :charset "utf-8"}, :body nil, :scheme :http, :request-method :post}}
	at clojure.core$ex_info.invokeStatic(core.clj:4617)
	at clojure.core$ex_info.invoke(core.clj:4617)
	at muuntaja.core$fail_on_request_decode_exception.invokeStatic(core.clj:236)
	at muuntaja.core$fail_on_request_decode_exception.invoke(core.clj:230)
	at muuntaja.core$decode_request_body.invokeStatic(core.clj:369)
	at muuntaja.core$decode_request_body.invoke(core.clj:363)
	at muuntaja.core$decode_request.invokeStatic(core.clj:379)
	at muuntaja.core$decode_request.invoke(core.clj:376)
	at muuntaja.core$format_request.invokeStatic(core.clj:387)
	at muuntaja.core$format_request.invoke(core.clj:384)
	at muuntaja.middleware$wrap_format_request$fn__31336.invoke(middleware.clj:113)
	at kekkonen.middleware$wrap_exceptions$fn__32593.invoke(middleware.clj:74)
	at muuntaja.middleware$wrap_format_response$fn__31340.invoke(middleware.clj:131)
	at muuntaja.middleware$wrap_format_negotiate$fn__31333.invoke(middleware.clj:95)
	at kekkonen.middleware$wrap_keyword_keys$fn__32602.invoke(middleware.clj:106)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__30330.invoke(keyword_params.clj:35)
	at ring.middleware.nested_params$wrap_nested_params$fn__30502.invoke(nested_params.clj:86)
	at ring.middleware.params$wrap_params$fn__30592.invoke(params.clj:64)
	at clojure.lang.Var.invoke(Var.java:379)
	at org.httpkit.server.HttpHandler.run(RingHandler.java:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: clojure.lang.ExceptionInfo: Malformed application/json in :muuntaja/decode {:type :muuntaja/decode, :format "application/json"}
	at clojure.core$ex_info.invokeStatic(core.clj:4617)
	at clojure.core$ex_info.invoke(core.clj:4617)
	at muuntaja.core$on_exception.invokeStatic(core.clj:66)
	at muuntaja.core$on_exception.invoke(core.clj:64)
	at muuntaja.core$create_coder$f__31187.invoke(core.clj:106)
	at muuntaja.core$decode_request_body.invokeStatic(core.clj:367)
	... 20 more
Caused by: java.lang.IllegalArgumentException: No implementation of method: :as-input-stream of protocol: #'muuntaja.protocols/AsInputStream found for class: nil
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:568)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:560)
	at muuntaja.protocols$eval30740$fn__30741$G__30731__30746.invoke(protocols.clj:45)
	at muuntaja.core$create_coder$f__31187.invoke(core.clj:104)
	... 21 more
```

**Comment by ikitommi** [comment]
Is this issue related? https://github.com/metosin/muuntaja/issues/33

**Comment by miikka** [comment]
Right, I didn't realize it's configurable! Might be needed to be enabled for Kekkonen.

**Comment by ikitommi** [comment]
Should the default be changed? e.g. being useful over correct.

**Comment by miikka** [comment]
`:allow-empty-input-on-decode?` does not actually work, because at least with Aleph and http-kit the request map contains `:body nil` if the body is empty. The implementation for `:allow-empty-input-on-decode?` assumes that's there's an empty InputStream.

**Comment by ikitommi** [comment]
ohmy. Per today I think the flag should be true as dwfault.
